[project]
name = "occhio"
version = "0.2.0"
description = "Experiment with Toy Models of Superposition"
requires-python = ">=3.10"
dependencies = [
    "torch>=2.10.0",
    "numpy>=2.2.6",
    "ipykernel>=7.2.0",
    "plotly>=6.5.2",
    "nbformat>=5.10.4",
    "einops>=0.8.2",
    "jupyterlab>=4.5.3",
    "debugpy>=1.8.20",
    "scipy>=1.15.3",
    "tqdm>=4.67.3",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "jupyter>=1.1.1",
    "kaleido>=1.2.0",
    "matplotlib>=3.10.8",
    "mkdocs>=1.6.1",
    "nbformat>=5.10.4",
    "plotly>=6.5.2",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.15.0",
    "seaborn>=0.13.2",
    "ty>=0.0.14",
]
docs = [
    "sphinx>=8.1.3",
    "myst-parser>=4.0.1",
    "sphinx-autobuild>=2024.10.3",
    "sphinx-rtd-theme>=3.1.0",
]

[tool.pytest.ini_options]
pythonpath = ["src"]


# For read the docs deployment with pip
[project.optional-dependencies]
docs = [
    "sphinx>=8.1.3",
    "myst-parser>=4.0.1",
    "sphinx-autobuild>=2024.10.3",
    "sphinx-rtd-theme>=3.1.0",
]