"""Manifold-based feature distributions.

Features are arranged on a sphere (or circle in 1-D) or a torus. A data point
is generated by picking a random point and activation magnitude; nearby features
activate with a cosine profile controlled by a length-scale parameter.
"""

import math

import torch
from torch import Tensor

from .base import Distribution


class ManifoldDistribution(Distribution):
    """Features arranged on a sphere with cosine-bump activation.

    ``n_features`` points are placed on a ``manifold_dim``-dimensional unit sphere with approximately equal spacing.  To generate a sample we draw a random direction **θ** and magnitude *m*.  The feature at position **v_φ** activates as

        x_φ = m · cos(α / ℓ)   if α / ℓ ≤ π/2,  else 0

    where α = arccos(v_φ · v_θ) is the geodesic distance and ℓ is the
    length-scale.

    Args:
        n_features: Number of features (points on the sphere).
        length_scale: Controls the width of the cosine bump.  Smaller values give sparser activations.
        manifold_dim: Dimension of the sphere the features live on.
            ``1`` → circle (S¹), ``2`` → ordinary sphere (S²), etc.
        magnitude_range: ``(low, high)`` for the uniform magnitude distribution.
        **kwargs: Passed to ``Distribution`` (device, generator).
    """

    def __init__(
        self,
        n_features: int,
        length_scale: float = 1.0,
        manifold_dim: int = 1,
        magnitude_range: tuple[float, float] = (0.9, 1.0),
        **kwargs,
    ):
        super().__init__(n_features, **kwargs)
        self.length_scale = length_scale
        self.manifold_dim = manifold_dim
        self.magnitude_range = magnitude_range

        # Place features on the sphere
        self.feature_positions = (
            self._place_features()
        )  # (n_features, manifold_dim + 1)

    def _place_features(self) -> Tensor:
        """Place ``n_features`` points approximately uniformly on S^{manifold_dim}."""
        if self.manifold_dim == 1:
            return self._place_on_circle()
        elif self.manifold_dim == 2:
            return self._place_on_sphere_fibonacci()
        else:
            return self._place_on_sphere_random()

    def _place_on_circle(self) -> Tensor:
        """Equal angular spacing on S¹."""
        angles = torch.linspace(
            0, 2 * math.pi, self.n_features + 1, device=self.device
        )[:-1]
        return torch.stack([torch.cos(angles), torch.sin(angles)], dim=-1)

    def _place_on_sphere_fibonacci(self) -> Tensor:
        """Fibonacci-lattice points on S² (approximately uniform)."""
        n = self.n_features
        golden = (1 + math.sqrt(5)) / 2
        i = torch.arange(n, device=self.device, dtype=torch.float)
        theta = torch.acos(1 - 2 * (i + 0.5) / n)
        phi = 2 * math.pi * i / golden
        return torch.stack(
            [
                torch.sin(theta) * torch.cos(phi),
                torch.sin(theta) * torch.sin(phi),
                torch.cos(theta),
            ],
            dim=-1,
        )

    def _place_on_sphere_random(self) -> Tensor:
        """Random points on S^{manifold_dim} via normalized Gaussians."""
        d = self.manifold_dim + 1
        pts = torch.randn(self.n_features, d, device=self.device)
        return pts / pts.norm(dim=-1, keepdim=True)

    def _sample_direction(self, batch_size: int) -> Tensor:
        """Sample a uniformly random direction on S^{manifold_dim}."""
        d = self.manifold_dim + 1
        v = self._randn(batch_size, d)
        return v / v.norm(dim=-1, keepdim=True)

    def sample(self, batch_size: int) -> Tensor:
        # Random direction: (batch, d)
        direction = self._sample_direction(batch_size)

        # Dot product with all feature positions: (batch, n_features)
        # Clamp to [-1, 1] for numerical safety in arccos
        dots = (direction @ self.feature_positions.T).clamp(-1.0, 1.0)

        # Geodesic angle: (batch, n_features)
        alpha = torch.acos(dots)

        # Cosine bump with length-scale
        scaled = alpha / self.length_scale
        activation = torch.cos(scaled)
        activation[scaled > math.pi / 2] = 0.0

        # Random magnitude: (batch, 1)
        lo, hi = self.magnitude_range
        m = lo + (hi - lo) * self._rand(batch_size, 1)

        return m * activation


class TorusDistribution(Distribution):
    """Features arranged on a flat torus T^d = S¹ × … × S¹ with cosine-bump activation.

    ``n_features`` points are placed on a uniform grid on the ``torus_dim``-dimensional
    torus.  To generate a sample we draw a random point **θ** ∈ [0, 2π)^d and
    magnitude *m*.  The feature at angular position **φ** activates as

        x_φ = m · cos(d(θ, φ) / ℓ)   if d(θ, φ) / ℓ ≤ π/2,  else 0

    where d(θ, φ) is the geodesic (flat-torus) distance and ℓ is the length-scale.

    For ``torus_dim > 1`` the number of features must be a perfect
    ``torus_dim``-th power so that a regular grid can be formed (e.g. 16 features
    on T² → 4 × 4 grid).

    Args:
        n_features: Number of features. Must be a perfect ``torus_dim``-th power
            when ``torus_dim > 1``.
        length_scale: Controls the width of the cosine bump. Smaller values
            give sparser activations.
        torus_dim: Number of circular factors (1 → circle, 2 → T², etc.).
        magnitude_range: ``(low, high)`` for the uniform magnitude distribution.
        **kwargs: Passed to ``Distribution`` (device, generator).
    """

    def __init__(
        self,
        n_features: int,
        length_scale: float = 1.0,
        torus_dim: int = 1,
        magnitude_range: tuple[float, float] = (0.9, 1.0),
        **kwargs,
    ):
        super().__init__(n_features, **kwargs)
        self.length_scale = length_scale
        self.torus_dim = torus_dim
        self.magnitude_range = magnitude_range

        # Validate and compute grid size
        k = round(n_features ** (1.0 / torus_dim))
        if k**torus_dim != n_features:
            raise ValueError(
                f"n_features={n_features} is not a perfect {torus_dim}-th power. "
                f"Closest valid count is {k**torus_dim}."
            )
        self.grid_size = k

        # Place features on the torus: (n_features, torus_dim) angles in [0, 2π)
        self.feature_angles = self._place_features()

    def _place_features(self) -> Tensor:
        """Place features on a uniform grid on T^d."""
        angles_per_dim = torch.linspace(
            0, 2 * math.pi, self.grid_size + 1, device=self.device
        )[:-1]

        if self.torus_dim == 1:
            return angles_per_dim.unsqueeze(-1)

        # Build d-dimensional grid via cartesian product
        grids = [angles_per_dim] * self.torus_dim
        mesh = torch.meshgrid(*grids, indexing="ij")
        return torch.stack([m.reshape(-1) for m in mesh], dim=-1)

    def _torus_distance(self, a: Tensor, b: Tensor) -> Tensor:
        """Geodesic distance on the flat torus.

        Args:
            a: (..., torus_dim) angles in [0, 2π).
            b: (..., torus_dim) angles in [0, 2π).

        Returns:
            (...) L2 norm of wrapped angular differences.
        """
        diff = (a - b).abs()
        wrapped = torch.minimum(diff, 2 * math.pi - diff)
        return wrapped.norm(dim=-1)

    def sample(self, batch_size: int) -> Tensor:
        # Random point on T^d: (batch, torus_dim)
        theta = 2 * math.pi * self._rand(batch_size, self.torus_dim)

        # Distance to each feature: (batch, n_features)
        # theta: (batch, 1, d), feature_angles: (n_features, d)
        dist = self._torus_distance(
            theta.unsqueeze(1), self.feature_angles.unsqueeze(0)
        )

        # Cosine bump with length-scale
        scaled = dist / self.length_scale
        activation = torch.cos(scaled)
        activation[scaled > math.pi / 2] = 0.0

        # Random magnitude: (batch, 1)
        lo, hi = self.magnitude_range
        m = lo + (hi - lo) * self._rand(batch_size, 1)

        return m * activation
